### ISSUE TITLE
test image with score

### ISSUE THREAD

**Issue by fisakhan** [meilfang/LMFD-PAD#5]
Can you please upload a test image with a score for verification purposes? I want to verify that I'm doing right.

**Comment by meilfang** [comment]
Hey, sorry for the later reply. I uploaded one bona fide and attack image in folder testing_images and also test.py (including my test prediction scores). It should be noticed that 1) the input image should be cropped face. 2) each model has different threshold to decide if an image is bona fide or attack.

**Comment by fisakhan** [comment]
Thanks @meilfang
