### ISSUE TITLE
I trained and tested in Oulu protocol 2, but the Acer is about 0.5. I don't know what went wrong?

### ISSUE THREAD

**Issue by Aluooooo** [meilfang/LMFD-PAD#7]
I trained and tested in Oulu protocol 2, but the Acer is about 0.5. I don't know what went wrong?

**Comment by Aluooooo** [comment]
apcer=1.0000, bpcer= 0.0000, acer= 0.5000

**Comment by Aluooooo** [comment]
I had found where I was worng, thank you!

**Comment by Aluooooo** [comment]
哥们你微信多少，我加你

**Comment by Aluooooo** [comment]
老乡不讲英格利希

**Comment by bumie7758258** [comment]
zjshz123

**Comment by bumie7758258** [comment]
zJshz123

**Comment by bumie7758258** [comment]
发你了老哥，第二个字母大写

**Comment by xb9919** [comment]
你好我最近尝试复现这个工作的时候也碰到这个问题了 能请教一下你们是怎么解决的么@Aluooooo @bumie7758258
